FROM maven:3.8.4-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/appointment-service-1.0-SNAPSHOT.jar app.jar
EXPOSE 3002
ENTRYPOINT ["java", "-jar", "app.jar"]
